In [6]:
import numpy as np

In [7]:
def apply_vander(num_list,N=0,increasing=False):
    if N == 0:
        N = len(num_list)
    vander_list = []
    for i in range(N):
        colm_list = []
        for j in range(len(num_list)):
            colm_list.append(num_list[j]**(N-1-i))
        if increasing == True:
            vander_list.insert(0,colm_list)
        else:
            vander_list.append(colm_list)
    return vander_list

In [8]:
vander_list = apply_vander([1,2,3,4,5],5)                                          # result 1 as vander numpy array
np.column_stack(vander_list) 

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [9]:
vander_list = apply_vander([1,2,3,4,5],increasing=True)                           # result 2 as vander numpy array
np.column_stack(vander_list) 

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [10]:
vander_list = apply_vander([1,2,3,4,5])                                           # result 3 as vander matrix
vander_matrix = np.matrix(vander_list)
vander_matrix.T  

matrix([[  1,   1,   1,   1,   1],
        [ 16,   8,   4,   2,   1],
        [ 81,  27,   9,   3,   1],
        [256,  64,  16,   4,   1],
        [625, 125,  25,   5,   1]])